### ISSUE TITLE
helmDefaults shouldn't be required

### ISSUE THREAD

**Issue by EmilAnker89** [tonsV2/helmstack#18]
```
PS C:\Users\EAJ\hello-stack> helmstack -b "helm tiller run helm" sync
unacceptable character #x0000: special characters are not allowed
  in "helmstack.yaml", position 3
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\helmstack.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python37\lib\site-packages\helmstack.py", line 60, in cli
    if 'helmDefaults' in stack:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by EmilAnker89** [comment]
something invalid about the helmstack yaml specification - maybe worth adding a bit of validation.
