### ISSUE TITLE
Overlay required

### ISSUE THREAD

**Issue by tonsV2** [tonsV2/helmstack#4]
If an environment is set but no overlay key found the following error occurs. Overlays shouldn't be mandatory.

Traceback (most recent call last):
  File "/home/nine/.local/bin/helmstack", line 11, in <module>
    load_entry_point('helmstack==1.1.1', 'console_scripts', 'helmstack')()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/nine/.local/lib/python2.7/site-packages/helmstack.py", line 65, in cli
    merge_overlays()
  File "/home/nine/.local/lib/python2.7/site-packages/helmstack.py", line 100, in merge_overlays
    merge(config.stack['releases'], config.overlay['releases'])
  File "/home/nine/.local/lib/python2.7/site-packages/helmstack.py", line 109, in merge
    release_overlay = overlays[name]
KeyError: 'postgresql'

**Comment by tonsV2** [comment]
Overlay no longer required
